{
 "title": "Air quality",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CO2 Current",
   "type": "gauge",
   "description": "Current CO2 reading independent of dashboard time range",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT co2 AS \"CO2\"\nFROM airquality\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "PM_2.5 Current",
   "type": "gauge",
   "description": "Current PM 2.5 (compensated) reading independent of dashboard time range",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT pm_025_comp AS \"PM_2.5\"\nFROM airquality\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "VOCs Current",
   "type": "gauge",
   "description": "Current TVOC index reading independent of dashboard time range",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT tvoc_index AS \"TVOC\"\nFROM airquality\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "bargauge",
   "description": "Current temperature reading independent of dashboard time range",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT temperature_c AS \"Temp\"\nFROM airquality\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Hum %",
   "type": "bargauge",
   "description": "Current relative humidity reading independent of dashboard time range",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT humidity_pct AS \"Humidity\"\nFROM airquality\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "description": "CO2 readings colored by same scheme as Airgradient official dashboards (as of 2025-12)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, co2 as \"Excellent\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND co2 < 800\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, co2 as \"Acceptable\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND co2 >= 800 AND co2 < 1000\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, co2 as \"Not ideal\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND co2 >= 1000 AND co2 < 1500\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, co2 as \"To be avoided\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND co2 >= 1500\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "VOCs",
   "type": "timeseries",
   "description": "TVOC Index readings colored by same scheme as Airgradient official dashboards (as of 2025-12)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, tvoc_index as \"Good\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND tvoc_index < 140\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, tvoc_index as \"Acceptable\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND tvoc_index >= 140 AND tvoc_index < 250\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, tvoc_index as \"Undesirable\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND tvoc_index >= 250 AND tvoc_index < 400\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, tvoc_index as \"High\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND tvoc_index >= 400\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature readings colored by same scheme as Airgradient official dashboards (as of 2025-12)",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Freezing\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c < 0\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Cold\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c >= 0 AND temperature_c < 10\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Cool\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c >= 10 AND temperature_c < 15\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Fresh\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c >= 15 AND temperature_c < 18\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Room\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c >= 18 AND temperature_c < 20\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Warm\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c >= 20 AND temperature_c < 23\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Stuffy\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c >= 23 AND temperature_c < 25\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Hot\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c >= 25\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "noxM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  MAX(nox_index) AS \"NOX\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo;"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Relative humidity readings colored by same scheme as Airgradient official dashboards (as of 2025-12)",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, humidity_pct as \"Arid\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND humidity_pct < 20\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, humidity_pct as \"Dry\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND humidity_pct >= 20 AND humidity_pct < 30\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, humidity_pct as \"Normal\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND humidity_pct >= 30 AND humidity_pct < 50\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, humidity_pct as \"Damp\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND humidity_pct >= 50 AND humidity_pct < 60\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, humidity_pct as \"Humid\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND humidity_pct >= 60 AND humidity_pct < 70\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, humidity_pct as \"Wet\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND humidity_pct >= 70\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Stuffy\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c >= 23 AND temperature_c < 25\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, temperature_c as \"Hot\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND temperature_c >= 25\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "PM_2.5 (mass)",
   "type": "timeseries",
   "description": "PM 2.5 (compensated) readings colored by same scheme as Airgradient official dashboards (as of 2025-12)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, pm_025_comp as \"Good\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND pm_025_comp < 6\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, pm_025_comp as \"Moderate\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND pm_025_comp >= 6 AND pm_025_comp < 12\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, pm_025_comp as \"Borderline\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND pm_025_comp >= 12 AND pm_025_comp < 18\nORDER BY time ASC;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT time, pm_025_comp as \"Unhealthy\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\n  AND pm_025_comp >= 18\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Particle Counts",
   "type": "timeseries",
   "description": "Particle counts per deciliter of air at 0.3, 1, 5, and 10 µm",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, pm_003_ct AS \"0.3 µm\",\n             pm_010_ct AS \"1 µm\",\n             pm_050_ct AS \"5 µm\",\n             pm_100_ct AS \"10 µm\"\nFROM airquality\nWHERE time >= $__timeFrom\n  AND time <= $__timeTo\nORDER BY time ASC;"
    }
   ]
  }
 ]
}